### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Isopod** [skalogryz/richmemo#7]
Unless I missed something, this repo does not appear to contain any license information. It looks like some of the source files are under LGPL, but not all of them include the blurb. I think it would be best to add a LICENSE file to the root of the repository, so that people can see the license at a glance and there is no ambiguity. Otherwise, many people will not be able to use this.

**Comment by skalogryz** [comment]
I've added the license files.
RichMemo is pretty much following LCL licenses (as it's heavily based on LCL code, such as TCustomMemo)
